yolo_model:

  config_file:
    name: yolov3_mission2.cfg
  weight_file:
    name: yolov3_mission2.backup
  threshold:
    value: 0.7
  detection_classes:
    names:
      - red
      - green
      - blue
      - orange
      - plate
